# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "marimo>=0.23.8",
#     "requests==2.34.2",
# ]
# ///

# pyright: reportUnusedExpression=false

import marimo

__generated_with = "0.23.9"
app = marimo.App(width="columns")


@app.cell(column=0, hide_code=True)
def _(mo):
    mo.md(r"""
    # View Pickled Data below
    """)
    return


@app.cell
def _(mo):
    pickle_run_btn = mo.ui.run_button()
    pickle_run_btn
    return (pickle_run_btn,)


@app.cell
def _(Path, mo, pickle, pickle_run_btn):
    mo.stop(not pickle_run_btn.value, mo.md("☝️ Click to read pickled data"))
    cwd = Path.cwd()
    if "data" in cwd.parts:
        cwd = cwd.parent

    data_file = cwd / "pokemon_gen1_data.pkl"
    with open(data_file, "rb") as f:
        pickled_data = pickle.load(f)

    [
        (mo.image(item["front_sprite"]), mo.image(item["back_sprite"]))
        for item in pickled_data
    ]
    return


@app.cell(column=1, hide_code=True)
def _(mo):
    mo.md(r"""
    ## The next several cells will hit make network requests

    Click the run button below to 'fire' them off.
    """)
    return


@app.cell
def _(mo):
    # marimo run button, good to block off expensive cells
    poke_run_btn = mo.ui.run_button()
    poke_run_btn
    return (poke_run_btn,)


@app.cell
def _(mo, poke_run_btn, requests_pokeapi):
    mo.stop(
        not poke_run_btn.value,
        mo.md("☝️ Click button for 'expensive' api calls"),
    )

    # get move data for bulbasaur
    # move_data = requests_pokeapi("https://pokeapi.co/api/v2/move/1")
    # move_data

    # get poke-api data for bulbasaur, all generations
    poke_data = requests_pokeapi("https://pokeapi.co/api/v2/pokemon/1")
    poke_data
    return


@app.cell
def _(mo, poke_run_btn, requests_get):
    mo.stop(not poke_run_btn.value, "idk? my bff j?")
    poke_sprites = {
        i: (
            mo.image(
                requests_get(
                    f"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/{i}.png"
                ).content
            ),
            mo.image(
                requests_get(
                    f"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/back/{i}.png"
                ).content
            ),
        )
        for i in range(1, 7)
    }
    # for i in range(1, 6):
    #     png_resp = requests_get(
    #         f"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/{i}.png"
    #         # f"https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-i/red-blue/transparent/back/{i}.png"
    #     )
    #     if png_resp.headers["content-type"].startswith("image"):
    #         poke_sprites[i] = png_resp.content
    #     else:
    #         print("http response was not a png image")
    # [mo.image(src=poke_sprites[i]) for i in poke_sprites.keys()]

    # # examples of how to read a byte->base64 encoded str back to python bytes
    # # the file is generated by another script
    # import base64

    # data = open_json_file("compiled_gen1_data.json")
    # # image = base64.b64decode(data[0]["front_sprite"])
    # [
    #     (
    #         base64.b64decode(data[i]["front_sprite"]),
    #         mo.image(base64.b64decode(data[i]["front_sprite"])),
    #         base64.b64decode(data[i]["back_sprite"]),
    #         mo.image(base64.b64decode(data[i]["back_sprite"])),
    #     )
    #     for i in range(0, POKE_ID_MAX)
    # ]

    poke_sprites
    return


@app.cell(column=2)
def utils():
    import pickle
    import time

    # from functools import lru_cache
    from pathlib import Path

    import marimo as mo
    import requests

    DELAY = 0.3

    # POKE_ID_MAX = 151


    @mo.cache
    def requests_get(url: str):
        time.sleep(DELAY)
        return requests.get(url, timeout=10)


    # @lru_cache(maxsize=None)
    def requests_pokeapi(url: str) -> dict:
        """GET with basic error handling. Cached by URL — repeated calls are free."""
        resp = requests_get(url)
        if not resp.ok:
            print(
                f"Error fetching from api, HTTP Code: {resp.status_code}. {resp.raw}"
            )
            return {}

        return resp.json()

    return Path, mo, pickle, requests_get, requests_pokeapi


if __name__ == "__main__":
    app.run()
